# OA管理項目配置文件

OaDictURL = "/camel/rest/oa/dicts"
OaDictsTypesListURL = "/camel/rest/oa/dicts/types/list"
CategoryURL = "/camel/rest/categorys"
WorkflowURL = "/camel/rest/workflow"
WorkflowSuspendURL = "/camel/rest/workflow/suspend?key="
WorkflowActivateURL = "/camel/rest/workflow/activate?key="
WorkflowMainWorkURL = "/camel/rest/categorys/getAll"
WorkflowHistoryURL = "/camel/rest/workflow/historys"
MyInvolvedURL = "/camel/rest/workflow/myInvolvedHistory"
MyHistoryURL = "/camel/rest/workflow/myHistory"
TaskURL = "/camel/rest/workflow/tasks"
TaskFormURL = "/camel/rest/workflow/form?taskId="
TaskActivitiesURL = "/camel/rest/workflow/activities?historyProcessId="

# 工作流流程地址
UserOrgsURL = "/camel/rest/users/[usersId]/orgs"
# 采购申请
PurchaseApplyURL = ""
PurchaseApplyStartURL = ""
# 用章申请
SealApplyURL  = "camel/rest/sealapplys"
SealApplyStartURL  = "/camel/rest/sealapplys/workflow/startProcess?id="
# 报销申请
ReimbursementApplyURL = "camel/rest/reimbursementapplys"
ReimbursementApplyStartURL = "camel/rest/reimbursementapplys/workflow/startProcess?id="
# 用人申请
RecruitApplyURL = "/camel/rest/recruitapplys"
RecruitApplyStartURL = "/camel/rest/recruitapplys/workflow/startProcess?id="
# 入职申请
EmployApplyURL = "/camel/rest/employapplys"
EmployApplyStartURL = "/camel/rest/employapplys/workflow/startProcess?id="
# 用车申请
CarApplyURL = "/camel/rest/carapplys"
CarApplyStartURL = "/camel/rest/carapplys/workflow/startProcess?id="
# 出差申请
EvectionApplyURL = "/camel/rest/evectionapplys"
EvectionApplyStartURL = "/camel/rest/evectionapplys/workflow/startProcess?id="
# 会议申请
MeetingApplyURL = "/camel/rest/meetingapplys"
MeetingApplyStartURL = "/camel/rest/meetingapplys/workflow/startProcess?id="
# 会议室申请
#MeetingRoomsURL  = "/camel/rest/meetingrooms"

# 临时申请
TempApplyURL  = "camel/rest/tempapplys"
TempApplyStartURL  = "/camel/rest/tempapplys/workflow/startProcess?id="

# 会议室申请
MeetingroomApplyURL  = "camel/rest/meetingroomapplys"
MeetingroomApplyStartURL  = "/camel/rest/meetingroomapplys/workflow/startProcess?id="

# 应聘人员管理
CandidateURL = "/camel/rest/candidates"
# 面试管理
InterviewURL = "/camel/rest/interviews"
# 试讲管理
LectureURL = "/camel/rest/lectures"

# 会议室
MeetingroomURL  = "camel/rest/meetingrooms"

# 需要自动注册成全局的Meetingroom组件
[[OaMeetingroomComponent]]
  path = "oa/meetingroom/meetingroomView"
  name = "OaMeetingroomView"
[[OaMeetingroomComponent]]
  path = "oa/meetingroom/meetingroomAdd"
  name = "OaMeetingroomAdd"
[[OaMeetingroomComponent]]
  path = "oa/meetingroom/meetingroomSearch"
  name = "OaMeetingroomSearch"

# 需要自动注册成全局的MeetingroomApply组件
[[OaMeetingroomApplyComponent]]
  path = "oa/meetingroomapply/meetingroomApplyView"
  name = "OaMeetingroomApplyView"
[[OaMeetingroomApplyComponent]]
  path = "oa/meetingroomapply/meetingroomApplyAdd"
  name = "OaMeetingroomApplyAdd"
[[OaMeetingroomApplyComponent]]
  path = "oa/meetingroomapply/meetingroomApplySearch"
  name = "OaMeetingroomApplySearch"

# 需要自动注册成全局的Category组件
[[OaCategoryComponent]]
  path = "oa/category/categoryView"
  name = "OaCategoryView"
[[OaCategoryComponent]]
  path = "oa/category/categoryAdd"
  name = "OaCategoryAdd"
[[OaCategoryComponent]]
  path = "oa/category/categorySearch"
  name = "OaCategorySearch"

# 需要自动注册成全局的PurchaseApply(采购申请)组件
[[PurchaseApplyComponent]]
  path = "oa/purchaseapply/purchaseApplyView"
  name = "OaPurchaseApplyView"
[[PurchaseApplyComponent]]
  path = "oa/purchaseapply/purchaseApplyAdd"
  name = "OaPurchaseApplyAdd"
[[PurchaseApplyComponent]]
  path = "oa/purchaseapply/purchaseApplySearch"
  name = "OaPurchaseApplySearch"

# 需要自动注册成全局的SealApply(用章申请)组件
[[SealApplyComponent]]
  path = "oa/sealapply/sealApplyView"
  name = "OaSealApplyView"
[[SealApplyComponent]]
  path = "oa/sealapply/sealApplyAdd"
  name = "OaSealApplyAdd"
[[SealApplyComponent]]
  path = "oa/sealapply/sealApplySearch"
  name = "OaSealApplySearch"

# 需要自动注册成全局的ReimbursementApply(报销申请)组件
[[ReimbursementApplyComponent]]
  path = "oa/reimbursementapply/reimbursementApplyView"
  name = "OaReimbursementApplyView"
[[ReimbursementApplyComponent]]
  path = "oa/reimbursementapply/reimbursementApplyAdd"
  name = "OaReimbursementApplyAdd"
[[ReimbursementApplyComponent]]
  path = "oa/reimbursementapply/reimbursementApplySearch"
  name = "OaReimbursementApplySearch"

# 需要自动注册成全局的ReimbursementApply(用人申请)组件
[[RecruitApplyComponent]]
  path = "oa/recruitapply/recruitApplyView"
  name = "OaRecruitApplyView"
[[RecruitApplyComponent]]
  path = "oa/recruitapply/recruitApplyAdd"
  name = "OaRecruitApplyAdd"
[[RecruitApplyComponent]]
  path = "oa/recruitapply/recruitApplySearch"
  name = "OaRecruitApplySearch"

# 需要自动注册成全局的EmployApply(入职申请)组件
[[EmployApplyComponent]]
  path = "oa/employapply/employApplyView"
  name = "OaEmployApplyView"
[[EmployApplyComponent]]
  path = "oa/employapply/employApplySearch"
  name = "OaEmployApplySearch"

# 需要自动注册成全局的CarApply(用车申请)组件
[[CarApplyComponent]]
  path = "oa/carapply/carApplyView"
  name = "OaCarApplyView"
[[CarApplyComponent]]
  path = "oa/carapply/carApplyAdd"
  name = "OaCarApplyAdd"
[[CarApplyComponent]]
  path = "oa/carapply/carApplySearch"
  name = "OaCarApplySearch"

# 需要自动注册成全局的EvectionApply(出差申请)组件
[[EvectionApplyComponent]]
  path = "oa/evectionapply/evectionApplyView"
  name = "OaEvectionApplyView"
[[EvectionApplyComponent]]
  path = "oa/evectionapply/evectionApplyAdd"
  name = "OaEvectionApplyAdd"
[[EvectionApplyComponent]]
  path = "oa/evectionapply/evectionApplySearch"
  name = "OaEvectionApplySearch"

# 需要自动注册成全局的MeetingApply(会议申请)组件
[[MeetingApplyComponent]]
  path = "oa/meetingapply/meetingApplyView"
  name = "OaMeetingApplyView"
[[MeetingApplyComponent]]
  path = "oa/meetingapply/meetingApplyAdd"
  name = "OaMeetingApplyAdd"
[[MeetingApplyComponent]]
  path = "oa/meetingapply/meetingApplySearch"
  name = "OaMeetingApplySearch"

# 需要自动注册成全局的TempApply(临时申请)组件
[[TempApplyComponent]]
  path = "oa/tempapply/tempApplyView"
  name = "OaTempApplyView"
[[TempApplyComponent]]
  path = "oa/tempapply/tempApplyAdd"
  name = "OaTempApplyAdd"
[[TempApplyComponent]]
  path = "oa/tempapply/tempApplySearch"
  name = "OaTempApplySearch"

# 需要自动注册成全局的Candidate(应聘人员管理)组件
[[CandidateComponent]]
  path = "oa/candidate/candidateView"
  name = "OaCandidateView"
[[CandidateComponent]]
  path = "oa/candidate/candidateAdd"
  name = "OaCandidateAdd"
[[CandidateComponent]]
  path = "oa/candidate/candidateSearch"
  name = "OaCandidateSearch"

# 需要自动注册成全局的Interview(面试管理)组件
[[InterviewComponent]]
  path = "oa/interview/interviewView"
  name = "OaInterviewView"
[[InterviewComponent]]
  path = "oa/interview/interviewAdd"
  name = "OaInterviewAdd"
[[InterviewComponent]]
  path = "oa/interview/interviewSearch"
  name = "OaInterviewSearch"

# 需要自动注册成全局的Lecture(试讲管理)组件
[[LectureComponent]]
  path = "oa/lecture/lectureView"
  name = "OaLectureView"
[[LectureComponent]]
  path = "oa/lecture/lectureAdd"
  name = "OaLectureAdd"
[[LectureComponent]]
  path = "oa/lecture/lectureSearch"
  name = "OaLectureSearch"

# workflow 的全局注册组件
[[OaWorkflowComponent]]
  path = "oa/comp/processHistorySearch"
  name = "OaProcessHistorySearch"
[[OaWorkflowComponent]]
  path = "oa/comp/processHistoryView"
  name = "OaProcessHistoryView"
[[OaWorkflowComponent]]
  path = "oa/comp/processDefinitionView"
  name = "OaProcessDefinitionView"
[[OaWorkflowComponent]]
  path = "oa/comp/taskView"
  name = "OaTaskView"
[[OaWorkflowComponent]]
  path = "oa/comp/taskComplete"
  name = "OaTaskComplete"

# workflow 的默认按钮定义
[[WorkflowButtonList]]
  id = "viewHistory"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证

# ProcessDefinition 的默认按钮定义
[[ProcessDefinitionButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ProcessDefinitionButtonList]]
  id = "suspend"
  title = "scope.suspensionState === 1 ? '运行' : '停止'"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true

# table 的附件按钮定义
[[AttachmentButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[AttachmentButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[AttachmentButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
[[AttachmentButtonList]]
  id = "attachment"
  title = "附件"
  isShow = true
  isPermission = true
