# 全局变量配置文件

cacheTime = 7200000 #缓存校验时间
baseURL = "http://localhost:8181"

systemApplicationsBaseURL = "/camel/rest/system/applications/"
loginUrl = "/login.jsp"
logoutUrl = "/logout"
applicationURL = "/camel/rest/system/applications"
msgCountURL = "/camel/rest/messages/polling/msgCount"
msgURL = "/camel/rest/messages/polling/msg"

#按钮 权限认证的地址
SecurityBtnUrl = "/camel/rest/system/applications/modules/children/buttons/"




ScheduleDictsURL = "/camel/rest/schedule/dicts"
ScheduleDictsTypesListURL = "/camel/rest/schedule/dicts/types/list"

# 附件管理请求地址
AttachmentURL="/camel/rest/attachments"
# 附件couchdb上传地址
uploadURL = "/camel/rest/upload"
# 附件couchdb删除地址
couchdbDelURL = "/camel/rest/couchdb"
# 组织机构树请求地址
orgURL = "/camel/rest/orgs"

# 全局table分页的配置
[PageConfig]
  sizes = [10, 20, 30, 40]
  limit = 10
  page = 1
  start = 0

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true

[[GlobalFilter]]
  path = "./components/filters/dictFilter.js"
  name = "getDictName"

[[GlobalComponent]]
  path = "./views/demo/world"
  name = "contact-us"
[[GlobalComponent]]
  path = "./components/table/search"
  name = "kalix-search"
[[GlobalComponent]]
  path = "./components/table/dialog"
  name = "kalix-dialog"
[[GlobalComponent]]
  path = "./components/table/wrapper"
  name = "kalix-wrapper"
[[GlobalComponent]]
  path = "./views/admin/user/userAdd"
  name = "KalixUserAdd"
[[GlobalComponent]]
  path = "./views/admin/user/userEdit"
  name = "KalixUserEdit"
[[GlobalComponent]]
  path = "./views/admin/user/userSearch"
  name = "userSearch"
# 附件管理
[[GlobalComponent]]
  path = "./components/custom/baseAttachmentDialog"
  name = "AttachmentDialog"
# 附件上传
[[GlobalComponent]]
  path = "./components/custom/baseUpload"
  name = "kalixUpload"
# 注册全局组件-组织机构树控件
[[GlobalComponent]]
  path = "./components/tree/basetree2"
  name = "orgTree"

# baseToolBar 的默认按钮定义
[[GlobalToolBarButtonList]]
  id = "add"
  icon = "icon-add"
  title = "添加"
  isShow = true
[[GlobalToolBarButtonList]]
  id = "deleteChecked"
  icon = "icon-delete"
  title = "删除选中"
  isShow = false
